# Generated by Django 3.0.8 on 2020-08-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sondage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sondage_title', models.CharField(max_length=300)),
                ('propostion_nom', models.CharField(max_length=300)),
                ('sondage_content', models.TextField()),
                ('vote_yes', models.IntegerField(default=0)),
                ('vote_no', models.IntegerField(default=0)),
                ('vote_null', models.IntegerField(default=0)),
                ('sondage_image', models.ImageField(upload_to='sondage_img/')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
