# Generated by Django 3.0.8 on 2020-08-18 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200818_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='home_number',
        ),
    ]
