# Generated by Django 3.0.8 on 2020-08-17 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actualite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='propostion_nom',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
