# Generated by Django 3.0.8 on 2020-08-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actualite', '0002_actualite_propostion_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actualite',
            old_name='lois_content',
            new_name='actu_content',
        ),
    ]
